require('plugin-configs.mason')
require('plugin-configs.mason-lspconfig')
require('plugin-configs.nvim-cmp')
require('plugin-configs.treesitter')
require('plugin-configs.fzf')
-- require('plugin-configs.nightfox')
require('plugin-configs.vscode')
require('plugin-configs.nvim-tree')
require('plugin-configs.lualine')
